language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - tip

sudo: false
cache: bundler

before_install:
  - pip install --user codecov
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test ./...
  - cd tokenizer; go test -benchmem -bench .; cd ..
  - cd internal/dic; go test -benchmem -bench .; cd ../..
  - /bin/sh ./go-coverall.sh

